package context

// vscodeEquivalenceClasses returns equivalence classes for vscode.
func vscodeEquivalenceClasses() []EquivalenceClass {
	return []EquivalenceClass{
		{
		Concept:    "VSCODE_EDITOR",
		Phrases:    []string{"editor model", "text model", "piece tree", "text buffer", "document model"},
		Targets:    []string{"TextModel", "PieceTreeTextBuffer", "PieceTreeBase", "TextBuffer", "ITextModel"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_DECORATION",
		Phrases:    []string{"decoration", "editor decoration", "inline decoration", "decoration type"},
		Targets:    []string{"Decoration", "DecorationsOverviewRuler", "InlineDecoration", "ModelDecorationOptions", "TrackedRangeStickiness"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_DIFF",
		Phrases:    []string{"diff algorithm", "diff editor", "line diff", "move detection", "diff computation"},
		Targets:    []string{"DiffAlgorithm", "DiffComputer", "LineSequence", "DetailedLineRangeMapping", "MovedText", "AdvancedLinesDiffComputer"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_DISPOSABLE",
		Phrases:    []string{"disposable", "dispose", "lifecycle", "cleanup", "leak detection"},
		Targets:    []string{"Disposable", "DisposableStore", "MutableDisposable", "toDisposable", "IDisposable", "dispose"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_EVENT",
		Phrases:    []string{"event emitter", "event listener", "on event", "fire event"},
		Targets:    []string{"Emitter", "Event", "EventBufferer", "EventMultiplexer", "onDidChange", "onWillChange"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_COMMAND",
		Phrases:    []string{"command", "keybinding", "keyboard shortcut", "command palette", "action"},
		Targets:    []string{"CommandsRegistry", "registerCommand", "KeybindingResolver", "ResolvedKeybindingItem", "Action"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_FOLDING",
		Phrases:    []string{"fold", "folding", "collapse region", "fold level", "code folding"},
		Targets:    []string{"FoldAction", "UnfoldAction", "FoldAllAction", "FoldLevelAction", "FoldingModel", "FoldingRegions"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_CODE_ACTION",
		Phrases:    []string{"code action", "quick fix", "auto fix", "refactor action", "code action provider"},
		Targets:    []string{"CodeActionOracle", "ManagedCodeActionSet", "getCodeActionProviders", "triggerCodeActionsForEditorSelection"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_THEME",
		Phrases:    []string{"color registry", "icon registry", "theme contribution", "register color", "color token"},
		Targets:    []string{"ColorRegistry", "ColorRegistry.registerColor", "ColorRegistry.resolveDefaultColor", "IconRegistry", "IconRegistry.registerIcon"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_CONFIG",
		Phrases:    []string{"configuration service", "settings file", "write configuration", "settings validation"},
		Targets:    []string{"ConfigurationEditing", "ConfigurationEditing.write", "ConfigurationEditing.getEdits"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_SCM",
		Phrases:    []string{"dirty diff", "scm gutter", "source control", "diff gutter", "change preview"},
		Targets:    []string{"DirtyDiffDecorator", "DirtyDiffWidget", "DiffActionRunner"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_KEYBINDING",
		Phrases:    []string{"keybinding conflict", "keyboard layout", "shortcut resolution", "keybinding schema"},
		Targets:    []string{"UserKeybindings", "KeybindingsJsonSchema", "ScanCodeKeyCodeMapper", "ScanCodeCombo"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_SUGGEST",
		Phrases:    []string{"suggest widget", "inline completion", "autocomplete", "ghost text", "completion provider"},
		Targets:    []string{"SuggestInlineCompletion", "InlineCompletionResults", "UpdateRequest", "renderLines"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
		{
		Concept:    "VSCODE_WORD_HIGHLIGHT",
		Phrases:    []string{"word highlight", "occurrence highlight", "cursor highlight", "word selection"},
		Targets:    []string{"WordHighlighter", "SelectionHighlighterState", "InsertCursorAtEndOfEachLineSelected"},
		TargetType: "symbol",
		Weight:     0.9,
		Source:     "framework",
		Lang:       "typescript",
		},
	}
}
