package context

// languageEquivalenceClasses returns equivalence concepts with language-specific
// target patterns. The universal classes use Go-centric targets (NewConfig,
// HandleError, ParseFlags). These extend them with Python, TypeScript, Rust,
// Java, and C# patterns so the same task description finds relevant symbols
// regardless of the repo's language.
//
// Cross-system benchmark (v0.6.0) showed knowing scoring 10.2% P@10 on
// Python/Rust/TS repos partly because keyword seeding missed language-specific
// symbol names. These classes directly address that gap.
func languageEquivalenceClasses() []EquivalenceClass {
	return []EquivalenceClass{
		// ---- Python / Django / Flask ----
		{
			Concept:    "PY_ENTRY_POINT",
			Phrases:    []string{"entry point", "app factory", "application", "wsgi", "asgi", "startup"},
			Targets:    []string{"create_app", "app", "application", "wsgi_app", "asgi_app", "__main__", "main"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_ROUTING",
			Phrases:    []string{"route", "url", "endpoint", "view", "handler", "request handler", "url pattern"},
			Targets:    []string{"route", "urlpatterns", "path", "url_for", "add_url_rule", "blueprint", "Blueprint", "before_request", "after_request", "app_errorhandler"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_MIDDLEWARE",
			Phrases:    []string{"middleware", "request processing", "before request", "after request", "hook", "interceptor"},
			Targets:    []string{"before_request", "after_request", "before_app_request", "process_request", "process_response", "process_view", "process_exception", "teardown_request", "middleware"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_ORM",
			Phrases:    []string{"database", "query", "model", "orm", "queryset", "migration", "schema"},
			Targets:    []string{"QuerySet", "Manager", "Model", "objects", "filter", "exclude", "annotate", "aggregate", "get_queryset", "Meta", "ForeignKey", "ManyToManyField", "migration", "RunSQL", "RunPython"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_SERIALIZATION",
			Phrases:    []string{"serialization", "serializer", "schema", "validation", "form", "marshal"},
			Targets:    []string{"Serializer", "ModelSerializer", "Schema", "Form", "ModelForm", "Field", "validate", "clean", "to_representation", "to_internal_value"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_AUTH",
			Phrases:    []string{"authentication", "authorization", "login", "permission", "session", "user"},
			Targets:    []string{"authenticate", "login", "logout", "login_required", "permission_required", "is_authenticated", "get_user", "AnonymousUser", "AbstractUser", "PermissionMixin", "has_perm"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_TEMPLATE",
			Phrases:    []string{"template", "render", "view", "context", "response"},
			Targets:    []string{"render_template", "render", "render_to_response", "TemplateView", "get_context_data", "template_name", "get_template_names"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_ERROR",
			Phrases:    []string{"error", "exception", "error handling", "abort", "error handler"},
			Targets:    []string{"HTTPException", "ValidationError", "abort", "errorhandler", "handle_exception", "app_errorhandler", "Http404", "PermissionDenied", "SuspiciousOperation"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_CONFIG",
			Phrases:    []string{"configuration", "settings", "config", "environment"},
			Targets:    []string{"settings", "config", "from_object", "from_envvar", "INSTALLED_APPS", "MIDDLEWARE", "DATABASES", "SECRET_KEY", "DEBUG", "BaseSettings"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "PY_TESTING",
			Phrases:    []string{"test", "testing", "fixture", "mock", "assert"},
			Targets:    []string{"TestCase", "SimpleTestCase", "TransactionTestCase", "setUp", "tearDown", "client", "RequestFactory", "pytest", "fixture", "parametrize", "mock", "patch"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- Django Framework (specific class mappings) ----
		{
			Concept:    "DJANGO_VALIDATORS",
			Phrases:    []string{"field validator", "email validation", "validate email", "custom validator", "input validation", "form validation"},
			Targets:    []string{"EmailValidator", "BaseValidator", "RegexValidator", "URLValidator", "ValidationError", "MaxValueValidator", "MinValueValidator"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_TEMPLATE_TAGS",
			Phrases:    []string{"template filter", "template tag", "custom filter", "custom tag", "templatetags"},
			Targets:    []string{"Library", "Library.filter", "Library.simple_tag", "Library.inclusion_tag", "FilterExpression", "register"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_MIDDLEWARE",
			Phrases:    []string{"django middleware", "request middleware", "custom middleware", "middleware class", "middleware chain"},
			Targets:    []string{"MiddlewareMixin", "SecurityMiddleware", "BaseHandler", "get_response", "process_request", "process_response", "CsrfViewMiddleware", "SessionMiddleware"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_CUSTOM_FIELD",
			Phrases:    []string{"custom field", "model field", "custom model field", "field type", "database field"},
			Targets:    []string{"Field", "CharField", "Field.deconstruct", "Field.from_db_value", "Field.get_prep_value", "Field.contribute_to_class", "ModelState"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_MANAGEMENT_CMD",
			Phrases:    []string{"management command", "django command", "custom command", "cli command"},
			Targets:    []string{"BaseCommand", "BaseCommand.handle", "BaseCommand.add_arguments", "OutputWrapper", "call_command", "CommandParser"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_SIGNALS",
			Phrases:    []string{"signal", "django signal", "post save", "pre save", "signal handler", "receiver"},
			Targets:    []string{"Signal", "Signal.send", "Signal.connect", "receiver", "post_save", "pre_save", "post_delete", "pre_delete", "request_finished"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_DB_BACKEND",
			Phrases:    []string{"database backend", "database connection", "database wrapper", "connection pool", "database cursor"},
			Targets:    []string{"BaseDatabaseWrapper", "BaseDatabaseWrapper.cursor", "BaseDatabaseWrapper.ensure_connection", "ConnectionHandler", "ConnectionRouter", "BaseDatabaseCreation", "BaseDatabaseOperations"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},
		{
			Concept:    "DJANGO_MIGRATIONS",
			Phrases:    []string{"migration", "schema migration", "database migration", "alter field", "add field", "migrate"},
			Targets:    []string{"Operation", "Operation.state_forwards", "Operation.database_forwards", "AlterField", "AddField", "ProjectState", "MigrationExecutor", "BaseDatabaseSchemaEditor"},
			TargetType: "symbol",
			Weight:     0.9,
			Source:     "framework",
		},

		// ---- TypeScript / JavaScript / React ----
		{
			Concept:    "TS_COMPONENT",
			Phrases:    []string{"component", "ui", "render", "view", "widget", "element"},
			Targets:    []string{"Component", "FC", "Props", "useState", "useEffect", "useRef", "useMemo", "useCallback", "render", "createElement"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_STATE",
			Phrases:    []string{"state", "store", "redux", "state management", "reducer", "action"},
			Targets:    []string{"store", "createStore", "reducer", "action", "dispatch", "useSelector", "useDispatch", "createSlice", "configureStore", "Provider"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_ROUTING",
			Phrases:    []string{"route", "router", "navigation", "page", "link"},
			Targets:    []string{"Router", "Route", "Switch", "useRouter", "useNavigate", "useParams", "Link", "NavLink", "createBrowserRouter", "Outlet"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_API",
			Phrases:    []string{"api", "fetch", "request", "http", "client", "endpoint"},
			Targets:    []string{"fetch", "axios", "useSWR", "useQuery", "useMutation", "createApi", "client", "request", "response", "interceptor"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_VALIDATION",
			Phrases:    []string{"validation", "schema", "type check", "parse", "transform"},
			Targets:    []string{"schema", "validate", "parse", "safeParse", "transform", "refine", "z.object", "z.string", "yup", "Joi"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_TYPE_SYSTEM",
			Phrases:    []string{"type", "interface", "generic", "type parameter", "inference", "narrowing", "declaration"},
			Targets:    []string{"Type", "TypeNode", "TypeChecker", "checker", "getTypeOfSymbol", "isTypeAssignableTo", "createType", "getSignatureFromDeclaration", "resolveSignature", "inferTypeArguments"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_COMPILER",
			Phrases:    []string{"compiler", "emit", "transform", "visitor", "node", "ast", "parse", "scanner"},
			Targets:    []string{"Transformer", "Visitor", "visitNode", "visitEachChild", "createSourceFile", "emitFiles", "transformNodes", "Scanner", "Parser", "createPrinter"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TS_MODULE",
			Phrases:    []string{"module", "import", "export", "resolution", "bundle", "package"},
			Targets:    []string{"resolveModuleName", "resolveModuleNames", "getResolvedModule", "moduleSpecifierToSourceFile", "createModuleSpecifierResolutionHost", "NodeModulePathResolver"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- Rust ----
		{
			Concept:    "RS_ERROR",
			Phrases:    []string{"error", "result", "error handling", "unwrap", "panic"},
			Targets:    []string{"Error", "Result", "anyhow", "thiserror", "From", "Display", "source", "context", "bail", "ensure"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RS_ASYNC",
			Phrases:    []string{"async", "await", "future", "runtime", "concurrent", "spawn"},
			Targets:    []string{"async", "await", "Future", "spawn", "block_on", "Runtime", "tokio", "poll", "Pin", "Waker"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RS_TRAITS",
			Phrases:    []string{"trait", "impl", "interface", "derive", "generic", "bound"},
			Targets:    []string{"impl", "trait", "From", "Into", "Display", "Debug", "Clone", "Default", "Serialize", "Deserialize"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RS_BUILD",
			Phrases:    []string{"build", "compile", "cargo", "dependency", "crate", "package", "manifest"},
			Targets:    []string{"resolve", "Resolve", "Registry", "Source", "SourceId", "PackageId", "Manifest", "Target", "CompileOptions", "BuildContext"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RS_BUILDER",
			Phrases:    []string{"builder", "config", "options", "construct", "new"},
			Targets:    []string{"Builder", "build", "new", "default", "with_", "set_", "Config", "Options"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RS_TESTING",
			Phrases:    []string{"test", "testing", "assert", "mock", "fixture"},
			Targets:    []string{"test", "cfg_test", "assert_eq", "assert_ne", "should_panic", "mock", "fixture", "proptest"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- Java / Spring ----
		{
			Concept:    "JAVA_CONTROLLER",
			Phrases:    []string{"controller", "endpoint", "api", "rest", "handler", "mapping"},
			Targets:    []string{"Controller", "RestController", "GetMapping", "PostMapping", "PutMapping", "DeleteMapping", "RequestMapping", "PathVariable", "RequestBody"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "JAVA_SERVICE",
			Phrases:    []string{"service", "business logic", "component", "bean", "inject"},
			Targets:    []string{"Service", "Component", "Bean", "Autowired", "Inject", "Transactional", "Repository"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "JAVA_DATA",
			Phrases:    []string{"repository", "database", "jpa", "entity", "query", "persistence"},
			Targets:    []string{"Repository", "JpaRepository", "CrudRepository", "Entity", "Table", "Column", "Query", "EntityManager", "Specification"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- Kubernetes / Infrastructure ----
		{
			Concept:    "K8S_CONTROLLER",
			Phrases:    []string{"controller", "reconcile", "operator", "custom resource", "watch"},
			Targets:    []string{"Reconcile", "Reconciler", "Controller", "controllerutil", "SetControllerReference", "Watch", "Owns", "For"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "K8S_SCHEDULER",
			Phrases:    []string{"scheduler", "scheduling", "pod placement", "node selection", "predicate", "priority"},
			Targets:    []string{"Schedule", "Scheduler", "Filter", "Score", "Preempt", "Bind", "Reserve", "Permit", "PreFilter", "PostFilter", "QueueSort"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "K8S_API",
			Phrases:    []string{"api server", "admission", "webhook", "api resource", "api group"},
			Targets:    []string{"Admit", "Validate", "Mutate", "AdmissionReview", "AdmissionResponse", "WebhookHandler", "Register", "AddToScheme", "GroupVersion"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "K8S_WORKLOAD",
			Phrases:    []string{"pod", "deployment", "statefulset", "daemonset", "job", "container"},
			Targets:    []string{"Pod", "PodSpec", "Container", "Deployment", "StatefulSet", "DaemonSet", "ReplicaSet", "Job", "CronJob"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- C# / ASP.NET / API Gateway ----
		{
			Concept:    "CS_MIDDLEWARE",
			Phrases:    []string{"middleware", "request pipeline", "invoke", "next middleware", "pipeline builder", "use middleware"},
			Targets:    []string{"Invoke", "InvokeAsync", "Middleware", "OcelotPipelineExtensions", "BuildOcelotPipeline", "UseMiddleware", "IApplicationBuilder"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_DI",
			Phrases:    []string{"dependency injection", "service registration", "di container", "service collection", "inject", "resolve", "wire up"},
			Targets:    []string{"IServiceCollection", "IServiceProvider", "AddSingleton", "AddTransient", "AddScoped", "AddOcelot", "OcelotBuilder", "OcelotBuilderExtensions", "ConfigureServices", "ServiceDescriptor"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_CONFIG",
			Phrases:    []string{"configuration", "options", "settings", "appsettings", "json config", "config file", "file configuration"},
			Targets:    []string{"IConfiguration", "IOptions", "FileConfiguration", "FileGlobalConfiguration", "FileRoute", "ConfigurationBuilder", "IConfigurationRoot", "FileConfigurationController"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_ROUTING",
			Phrases:    []string{"route", "routing", "downstream", "upstream", "path template", "url mapping", "request mapping"},
			Targets:    []string{"DownstreamRoute", "UpstreamPathTemplate", "DownstreamUrlCreatorMiddleware", "DownstreamPathPlaceholderReplacer", "IUrlPathToUrlPathMatcher", "RouteFinder", "RouteCreator"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_AUTH",
			Phrases:    []string{"authentication", "authorization", "claims", "jwt", "token", "scope", "policy"},
			Targets:    []string{"AuthenticationMiddleware", "AuthenticationOptions", "IClaimsAuthorizer", "IScopesAuthorizer", "ClaimsAuthorizer", "ScopesAuthorizer", "ClaimToThing", "AuthorizationMiddleware"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_LOADBALANCE",
			Phrases:    []string{"load balancing", "load balancer", "round robin", "least connections", "sticky session", "service discovery"},
			Targets:    []string{"ILoadBalancer", "ILoadBalancerCreator", "RoundRobin", "LeastConnection", "CookieStickySessions", "IServiceDiscoveryProvider", "ServiceDiscoveryFinderMiddleware"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_CACHE",
			Phrases:    []string{"cache", "caching", "output cache", "response cache", "cached response"},
			Targets:    []string{"IOcelotCache", "OutputCacheMiddleware", "CacheOptions", "DefaultMemoryCache", "CachedResponse", "ICacheKeyGenerator", "DefaultCacheKeyGenerator"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_RATELIMIT",
			Phrases:    []string{"rate limit", "rate limiting", "throttle", "throttling", "request limit"},
			Targets:    []string{"RateLimitingMiddleware", "RateLimitOptions", "RateLimitOptionsCreator", "IRateLimiting"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_HTTP_CLIENT",
			Phrases:    []string{"http client", "delegating handler", "http request", "http response", "downstream request", "request builder"},
			Targets:    []string{"HttpClientBuilder", "IDelegatingHandlerHandlerProvider", "DelegatingHandler", "IHttpRequester", "HttpClientHttpRequester", "DownstreamRequest", "HttpRequestMessage"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_QUALITY_OF_SERVICE",
			Phrases:    []string{"circuit breaker", "quality of service", "qos", "polly", "retry", "fault tolerance"},
			Targets:    []string{"IQoSProvider", "QoSProviderFactory", "PollyQoSProvider", "CircuitBreaker", "QoSOptions"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_HEADER_TRANSFORM",
			Phrases:    []string{"header", "header transformation", "find and replace", "add header", "remove header", "upstream header", "downstream header"},
			Targets:    []string{"IHttpResponseHeaderReplacer", "IHttpRequestHeaderReplacer", "AddHeader", "HeaderTransformations", "HttpResponseHeaderReplacer", "HeaderFindAndReplaceMiddleware"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_AGGREGATION",
			Phrases:    []string{"aggregation", "aggregate", "fan out", "merge responses", "request aggregator"},
			Targets:    []string{"IDefinedAggregator", "MultiplexingMiddleware", "UserDefinedResponseAggregator", "SimpleJsonResponseAggregator", "AggregateRoute"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_WEBSOCKET",
			Phrases:    []string{"websocket", "websockets", "ws proxy", "bidirectional", "socket"},
			Targets:    []string{"WebSocketsProxyMiddleware", "IWebSocketsFactory", "IClientWebSocketConnector", "PumpAsync"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_SECURITY",
			Phrases:    []string{"security", "ip whitelist", "ip blacklist", "ip filter", "access control", "security policy"},
			Targets:    []string{"SecurityMiddleware", "ISecurityPolicy", "IPSecurityPolicy", "SecurityOptions"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "CS_ERROR_HANDLING",
			Phrases:    []string{"error handling", "exception", "error response", "status code", "error middleware"},
			Targets:    []string{"ExceptionHandlerMiddleware", "ResponderMiddleware", "Error", "UnauthenticatedError", "UnauthorizedError", "UnableToFindDownstreamRouteError"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- FastAPI / Starlette ----
		{
			Concept:    "FASTAPI_DEPENDENCY",
			Phrases:    []string{"dependency", "depends", "dependency injection", "inject", "dependency override"},
			Targets:    []string{"Depends", "get_dependant", "solve_dependencies", "dependency_overrides", "DependencyOverrider", "SecurityScopes"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_ROUTER",
			Phrases:    []string{"router", "api router", "include router", "route", "endpoint", "path operation"},
			Targets:    []string{"APIRouter", "include_router", "add_api_route", "add_api_websocket_route", "api_route", "APIRoute"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_APP",
			Phrases:    []string{"fastapi app", "application", "openapi", "swagger", "docs"},
			Targets:    []string{"FastAPI", "build_middleware_stack", "openapi", "setup", "openapi_schema"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_BACKGROUND",
			Phrases:    []string{"background task", "background job", "after response", "async task"},
			Targets:    []string{"BackgroundTasks", "add_task", "BackgroundTask"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_UPLOAD",
			Phrases:    []string{"file upload", "upload file", "multipart", "form data"},
			Targets:    []string{"UploadFile", "File", "Form", "Body"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_VALIDATION",
			Phrases:    []string{"pydantic", "response model", "request validation", "validation error", "schema"},
			Targets:    []string{"RequestValidationError", "ResponseValidationError", "ValidationException", "BaseModel", "Field"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_EXCEPTION",
			Phrases:    []string{"exception handler", "error handler", "http exception", "error response"},
			Targets:    []string{"http_exception_handler", "request_validation_exception_handler", "HTTPException", "exception_handler", "exception_handlers"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_LIFESPAN",
			Phrases:    []string{"lifespan", "startup", "shutdown", "on event", "application lifecycle"},
			Targets:    []string{"on_event", "lifespan", "on_startup", "on_shutdown", "Router.lifespan_context"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_SECURITY",
			Phrases:    []string{"oauth", "bearer", "api key", "security", "authentication scheme"},
			Targets:    []string{"OAuth2PasswordBearer", "OAuth2PasswordRequestForm", "APIKeyHeader", "HTTPBearer", "SecurityScopes", "HTTPBasic"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "FASTAPI_WEBSOCKET",
			Phrases:    []string{"websocket", "ws", "websocket endpoint", "websocket route"},
			Targets:    []string{"WebSocket", "WebSocketRoute", "add_api_websocket_route", "WebSocketClose", "WebSocketException"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- Terraform / HCL / Infrastructure ----
		{
			Concept:    "TF_PROVIDER",
			Phrases:    []string{"provider", "provider configuration", "provider source", "provider plugin", "provider schema"},
			Targets:    []string{"Provider", "ProviderConfig", "AbsProviderConfig", "LocalProviderConfig", "NewDefaultProvider", "ParseProviderSourceString", "ImpliedProviderForUnqualifiedType"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_STATE",
			Phrases:    []string{"state", "state backend", "state storage", "state manager", "remote state", "state file"},
			Targets:    []string{"State", "statemgr", "Backend", "StateMgr", "StateStore", "Locker", "PersistentMeta"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_PLAN_APPLY",
			Phrases:    []string{"plan", "apply", "destroy", "refresh", "terraform plan", "terraform apply"},
			Targets:    []string{"PlanCommand", "ApplyCommand", "Operation", "ParseApply", "ParsePlan", "LoadPlanFile"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_GRAPH",
			Phrases:    []string{"dependency graph", "graph walk", "graph transformer", "dag", "topological", "directed graph"},
			Targets:    []string{"Graph", "Walker", "DirectedGraph", "TopologicalOrder", "AcyclicGraph", "BasicEdge", "TransitiveDependenciesOf", "TransitiveDependentsOf"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_RESOURCE",
			Phrases:    []string{"resource", "resource type", "resource instance", "resource address", "managed resource"},
			Targets:    []string{"Resource", "AbsResource", "AbsResourceInstance", "ResourceMode", "ManagedResourceMode", "ConfigResource"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_MODULE",
			Phrases:    []string{"module", "module call", "module source", "child module", "module instance"},
			Targets:    []string{"Module", "ModuleCall", "ModuleInstance", "ModuleSource", "ModuleSourceLocal", "ModuleSourceRegistry", "Loader"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_CONFIG",
			Phrases:    []string{"configuration", "hcl", "config file", "config loader", "terraform block"},
			Targets:    []string{"Config", "Module", "Loader", "Parser", "LoadConfig", "BuildConfig", "ModuleWalker"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_VARIABLE",
			Phrases:    []string{"variable", "input variable", "output", "output value", "local value"},
			Targets:    []string{"InputVariable", "OutputValue", "LocalValue", "AbsInputVariableInstance", "OutputCommand"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_PROVISIONER",
			Phrases:    []string{"provisioner", "remote exec", "local exec", "file provisioner"},
			Targets:    []string{"Provisioner", "NodeResourceProvisioner", "ResourceProvisioner"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_FORMAT",
			Phrases:    []string{"fmt", "format", "terraform fmt", "formatting", "hcl format"},
			Targets:    []string{"FmtCommand", "fmtcmd", "FormatCommand"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "TF_CLI",
			Phrases:    []string{"cli command", "terraform command", "subcommand", "command factory"},
			Targets:    []string{"Command", "initCommands", "listCommands", "Meta", "CommandFactory"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},

		// ---- Rust ----
		{
			Concept:    "RUST_SERDE",
			Phrases:    []string{"serialize", "deserialize", "json", "toml", "yaml", "marshal", "unmarshal", "parse config", "configuration file"},
			Targets:    []string{"serialize", "deserialize", "Serialize", "Deserialize", "from_str", "to_string", "serde_json", "from_reader", "to_writer"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_ERROR",
			Phrases:    []string{"error handling", "error type", "result", "propagate error", "error conversion", "custom error", "failure"},
			Targets:    []string{"Error", "Result", "anyhow", "bail", "context", "with_context", "map_err", "from", "source", "Display", "thiserror"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_ASYNC",
			Phrases:    []string{"async", "await", "concurrent", "parallel", "spawn", "runtime", "future", "task", "executor"},
			Targets:    []string{"spawn", "block_on", "Runtime", "Handle", "JoinHandle", "select", "tokio", "async_trait", "Future", "Poll", "Waker"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_TRAITS",
			Phrases:    []string{"implement trait", "derive", "trait bound", "generic", "type constraint", "interface", "abstract"},
			Targets:    []string{"impl", "Clone", "Debug", "Default", "Display", "From", "Into", "TryFrom", "TryInto", "Iterator", "IntoIterator", "AsRef", "Deref"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_COLLECTIONS",
			Phrases:    []string{"collection", "map", "set", "vector", "list", "hash map", "lookup", "store", "container"},
			Targets:    []string{"HashMap", "BTreeMap", "HashSet", "Vec", "VecDeque", "BinaryHeap", "insert", "get", "contains_key", "entry", "or_insert"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_IO",
			Phrases:    []string{"file", "read file", "write file", "io", "stream", "buffer", "path", "filesystem"},
			Targets:    []string{"File", "BufReader", "BufWriter", "Read", "Write", "open", "create", "read_to_string", "write_all", "PathBuf", "Path", "canonicalize"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_CLI",
			Phrases:    []string{"command line", "argument", "flag", "subcommand", "cli", "parse arguments", "options"},
			Targets:    []string{"Arg", "Command", "Parser", "Args", "Subcommand", "clap", "matches", "get_one", "get_many", "value_of"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_TESTING",
			Phrases:    []string{"test", "assert", "mock", "fixture", "integration test", "unit test"},
			Targets:    []string{"assert_eq", "assert_ne", "assert", "should_panic", "test", "cfg_test", "mock", "expect", "proptest", "quickcheck"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_CONCURRENCY",
			Phrases:    []string{"mutex", "lock", "thread", "channel", "sync", "atomic", "shared state", "send", "arc"},
			Targets:    []string{"Mutex", "RwLock", "Arc", "Rc", "mpsc", "channel", "Sender", "Receiver", "Atomic", "send", "recv", "lock", "try_lock"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_BUILDER",
			Phrases:    []string{"builder", "construct", "configure", "create", "initialize", "setup", "new instance"},
			Targets:    []string{"new", "builder", "build", "with_capacity", "default", "from_config", "configure", "set_", "with_"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_ITERATOR",
			Phrases:    []string{"iterate", "map", "filter", "collect", "fold", "chain", "transform", "pipeline", "stream processing"},
			Targets:    []string{"iter", "into_iter", "map", "filter", "collect", "fold", "flat_map", "chain", "enumerate", "zip", "take", "skip", "any", "all", "find"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
		{
			Concept:    "RUST_PACKAGE",
			Phrases:    []string{"dependency", "package", "crate", "module", "workspace", "manifest", "cargo.toml", "version", "registry"},
			Targets:    []string{"Package", "Manifest", "Dependency", "Workspace", "resolve", "Registry", "Source", "SourceId", "PackageId", "VersionReq"},
			TargetType: "symbol",
			Weight:     0.8,
			Source:     "language",
		},
	}
}
