package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	knowingctx "github.com/blackwell-systems/knowing/internal/context"
	"github.com/blackwell-systems/knowing/internal/store"
)

const generatedMarkerStart = "<!-- knowing:generated:start -->"
const generatedMarkerEnd = "<!-- knowing:generated:end -->"

// cmdInit generates a CLAUDE.md section with graph-derived project context.
// It is nondestructive and idempotent:
//   - If no CLAUDE.md exists, creates one with the generated section
//   - If CLAUDE.md exists without markers, appends the generated section
//   - If CLAUDE.md exists with markers, replaces only the section between markers
//   - Never touches content outside the markers
func cmdInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	dbPath := fs.String("db", "knowing.db", "Path to SQLite database")
	output := fs.String("output", "CLAUDE.md", "Output file path (default: CLAUDE.md in current directory)")
	budget := fs.Int("budget", 3000, "Token budget for context section")
	if err := fs.Parse(args); err != nil {
		return err
	}

	if _, err := os.Stat(*dbPath); os.IsNotExist(err) {
		return fmt.Errorf("database not found: %s (run 'knowing index' first)", *dbPath)
	}

	st, err := store.NewSQLiteStore(*dbPath)
	if err != nil {
		return fmt.Errorf("opening store: %w", err)
	}
	defer st.Close()

	// Generate the context section.
	section, err := generateContextSection(st, *budget)
	if err != nil {
		return fmt.Errorf("generating context: %w", err)
	}

	// Write or update the file.
	return writeNondestructive(*output, section)
}

// generateContextSection produces the knowing-generated content.
func generateContextSection(st *store.SQLiteStore, budget int) (string, error) {
	ctx := context.Background()
	engine := knowingctx.NewContextEngine(st)

	// Get top symbols by structural importance.
	block, err := engine.ForTask(ctx, knowingctx.TaskOptions{
		TaskDescription: "architecture overview important symbols",
		TokenBudget:     budget,
		Format:          "xml",
	})
	if err != nil {
		return "", err
	}

	// Count stats.
	allNodes, err := st.NodesByName(ctx, "")
	if err != nil {
		return "", err
	}

	// Group nodes by package.
	packages := make(map[string]int)
	for _, n := range allNodes {
		pkg := extractPackage(n.QualifiedName)
		if pkg != "" {
			packages[pkg]++
		}
	}

	// Sort packages by symbol count.
	type pkgCount struct {
		pkg   string
		count int
	}
	var sorted []pkgCount
	for pkg, count := range packages {
		sorted = append(sorted, pkgCount{pkg, count})
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].count > sorted[j].count
	})

	// Build the section.
	var sb strings.Builder
	sb.WriteString(generatedMarkerStart + "\n")
	sb.WriteString("## Project Graph (auto-generated by knowing)\n\n")
	sb.WriteString(fmt.Sprintf("**Indexed:** %d symbols across %d packages\n\n", len(allNodes), len(packages)))

	// Top packages.
	sb.WriteString("### Key Packages\n\n")
	sb.WriteString("| Package | Symbols |\n")
	sb.WriteString("|---------|--------|\n")
	limit := 15
	if len(sorted) < limit {
		limit = len(sorted)
	}
	for _, p := range sorted[:limit] {
		sb.WriteString(fmt.Sprintf("| `%s` | %d |\n", p.pkg, p.count))
	}
	sb.WriteString("\n")

	// Top symbols by score.
	if len(block.Symbols) > 0 {
		sb.WriteString("### Key Symbols (by structural importance)\n\n")
		shown := 20
		if len(block.Symbols) < shown {
			shown = len(block.Symbols)
		}
		for _, sym := range block.Symbols[:shown] {
			name := shortName(sym.Node.QualifiedName)
			sb.WriteString(fmt.Sprintf("- `%s` (%s) score=%.2f\n", name, sym.Node.Kind, sym.Score))
		}
		sb.WriteString("\n")
	}

	// Tool guidance.
	sb.WriteString("### Available Context Tools\n\n")
	sb.WriteString("This project has a knowing graph indexed. Use these MCP tools:\n\n")
	sb.WriteString("- `context_for_task` with your task description before complex edits\n")
	sb.WriteString("- `context_for_pr` with changed file list for PR review\n")
	sb.WriteString("- `blast_radius` to understand impact of a symbol change\n")
	sb.WriteString("- `cross_repo_callers` for cross-repo impact analysis\n")
	sb.WriteString("\nRequest `format: \"gcf\"` for 84% token savings on responses.\n")
	sb.WriteString(generatedMarkerEnd + "\n")

	return sb.String(), nil
}

// writeNondestructive writes the generated section without disrupting existing content.
func writeNondestructive(path, section string) error {
	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		// No file exists: create with the section.
		return os.WriteFile(path, []byte(section), 0644)
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}

	content := string(existing)

	// Check if markers already exist.
	startIdx := strings.Index(content, generatedMarkerStart)
	endIdx := strings.Index(content, generatedMarkerEnd)

	if startIdx >= 0 && endIdx >= 0 {
		// Replace between markers (inclusive).
		endIdx += len(generatedMarkerEnd)
		// Find the newline after the end marker.
		if endIdx < len(content) && content[endIdx] == '\n' {
			endIdx++
		}
		newContent := content[:startIdx] + section + content[endIdx:]
		return os.WriteFile(path, []byte(newContent), 0644)
	}

	// No markers: append the section with a separator.
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += "\n" + section
	return os.WriteFile(path, []byte(content), 0644)
}

// extractPackage gets the package path from a qualified name.
func extractPackage(qname string) string {
	// Format: repoURL://path.Symbol
	idx := strings.Index(qname, "://")
	if idx < 0 {
		return ""
	}
	rest := qname[idx+3:]
	dotIdx := strings.LastIndex(rest, ".")
	if dotIdx < 0 {
		return rest
	}
	return rest[:dotIdx]
}

// shortName extracts a readable short name from a qualified name.
func shortName(qname string) string {
	// Format: repoURL://path/to/pkg.Type.Method
	idx := strings.Index(qname, "://")
	if idx >= 0 {
		qname = qname[idx+3:]
	}
	// Take last two path components + symbol.
	parts := strings.Split(qname, "/")
	if len(parts) > 2 {
		parts = parts[len(parts)-2:]
	}
	result := filepath.Join(parts...)
	return result
}
