ALTER TABLE edges ADD COLUMN callsite_line INTEGER NOT NULL DEFAULT 0;
ALTER TABLE edges ADD COLUMN callsite_col INTEGER NOT NULL DEFAULT 0;
ALTER TABLE edges ADD COLUMN callsite_file TEXT NOT NULL DEFAULT '';
